// Generated by Xata Codegen 0.26.4. Please do not edit.
import { buildClient } from '@xata.io/client';
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from '@xata.io/client';

const tables = [
  {
    name: 'Events',
    columns: [
      {
        name: 'name',
        type: 'string',
        notNull: true,
        defaultValue: 'Event Name',
      },
      {
        name: 'description',
        type: 'text',
        notNull: true,
        defaultValue: 'Event Description',
      },
      { name: 'date', type: 'datetime', notNull: true, defaultValue: 'now' },
      { name: 'location', type: 'string' },
      {
        name: 'userId',
        type: 'string',
        notNull: true,
        defaultValue: 'User Id',
      },
    ],
    revLinks: [
      { column: 'event', table: 'Items' },
      { column: 'event', table: 'RSVPS' },
    ],
  },
  {
    name: 'Items',
    columns: [
      { name: 'event', type: 'link', link: { table: 'Events' } },
      { name: 'quantity', type: 'int', notNull: true, defaultValue: '1' },
      {
        name: 'name',
        type: 'string',
        notNull: true,
        defaultValue: 'Item Name',
      },
      { name: 'userId', type: 'string' },
    ],
  },
  {
    name: 'RSVPS',
    columns: [
      { name: 'event', type: 'link', link: { table: 'Events' } },
      {
        name: 'userId',
        type: 'string',
        notNull: true,
        defaultValue: 'User ID',
      },
      { name: 'status', type: 'string', notNull: true, defaultValue: 'GOING' },
    ],
  },
  {
    name: 'UserProfile',
    columns: [
      { name: 'username', type: 'string', notNull: true, defaultValue: '' },
      { name: 'name', type: 'string', notNull: true, defaultValue: 'Name' },
      { name: 'userId', type: 'string', notNull: true, defaultValue: 'userid' },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Events = InferredTypes['Events'];
export type EventsRecord = Events & XataRecord;

export type Items = InferredTypes['Items'];
export type ItemsRecord = Items & XataRecord;

export type Rsvps = InferredTypes['RSVPS'];
export type RsvpsRecord = Rsvps & XataRecord;

export type UserProfile = InferredTypes['UserProfile'];
export type UserProfileRecord = UserProfile & XataRecord;

export type DatabaseSchema = {
  Events: EventsRecord;
  Items: ItemsRecord;
  RSVPS: RsvpsRecord;
  UserProfile: UserProfileRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    'https://James-Q-Quick-s-workspace-l5kbra.us-east-1.xata.sh/db/potluck-pal',
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
